# Generated by Django 4.2.5 on 2023-10-05 23:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
